name: CI – Docker (multi-arch + render)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write  # for GHCR

env:
  GHCR_IMAGE: ghcr.io/${{ github.repository }}
  DH_IMAGE: dockerntonio/music-api
  CONTEXT: app
  DOCKERFILE: Dockerfile

  # Map secrets to env so we can use them in `if:` expressions
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

concurrency:
  group: docker-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU (emulation)
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        if: ${{ secrets.DOCKERHUB_USERNAME != '' && secrets.DOCKERHUB_TOKEN != '' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 1) Multi-arch build → :latest (Docker Hub + GHCR)
      - name: Build & push multi-arch :latest
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.CONTEXT }}
          file: ${{ env.DOCKERFILE }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.DH_IMAGE }}:latest
            ${{ env.GHCR_IMAGE }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # 2) amd64-only build → :render (Docker Hub + GHCR)
      - name: Build & push amd64-only :render
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.CONTEXT }}
          file: ${{ env.DOCKERFILE }}
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.DH_IMAGE }}:render
            ${{ env.GHCR_IMAGE }}:render
          cache-from: type=gha
          cache-to: type=gha,mode=max
