name: CI – Docker (multi-arch + render)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write  # needed for GHCR

env:
  GHCR_IMAGE: ghcr.io/${{ github.repository }}
  CONTEXT: app
  DOCKERFILE: ./Dockerfile

concurrency:
  group: docker-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Multi-arch build → :latest
      - name: Build & push multi-arch :latest
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.CONTEXT }}
          file: ${{ env.DOCKERFILE }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.GHCR_IMAGE }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # amd64-only build → :render
      - name: Build & push amd64-only :render
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.CONTEXT }}
          file: ${{ env.DOCKERFILE }}
          push: true
          platforms: linux/amd64
          tags: ${{ env.GHCR_IMAGE }}:render
          cache-from: type=gha
          cache-to: type=gha,mode=max
